[notes]
descriptions = [
  "The story takes place at Bongo and Oakley's house in a forest by a lake.",
  "The house is a cozy cabin with a fireplace, a big yard, and a dock leading to the lake.",
  "Neighboring towns offer plenty of opportunities for adventure, such as skiing, hiking, swimming, learning, and playing.",
  "There is a rustic and magical train station nearby that can take them to faraway places for adventures.",
  "Use humor similar to sponge bob square pants."
]

[plot]
descriptions = [
  "Bongo and Oakley first choose a real-world destination to travel to, so children can learn about different places.",
  "They embark on an adventure suitable for the chosen location.",
  "They stumble upon goofy characters and find themselves in humorous precarious situations.",
  "The story should be engaging, fun, and educational, with a focus on friendship, problem-solving, and teamwork.",
  "The story should be written in a way that children can relate to the characters and their adventures.",
  "By the end of the story they should have learned something new and have had a fun adventure."
  # "Along the way, they encounter a problem that requires math, science, and critical thinking to solve.",
  # "The problem should be solved by the end of the story, making children think about how they would solve it.",
  # "The story should have a happy ending and a moral or lesson appropriate for children aged 2-6 years old, without explicitly stating the moral at the end."
  # "During their adventure, they face various challenges and make new friends.",
]

[[characters]]
name = "Bongo"
descriptions = [
  "Bongo is an 11-year-old, 70-pound Bernese Mountain Dog. He is mostly black and loves to swim and play fetch.",
  "He runs fast, gets very excited at the lake, and is easygoing otherwise.",
  "He can be a bit vocal, especially when excited."
]

[[characters]]
name = "Oakley"
descriptions = [
  "Oakley is a 6-year-old, 110-pound Bernese Mountain Dog with a white 'Swiss kiss' on the back of his neck.",
  "He is more reserved than Bongo but very loyal and loves his toys.",
  "Oakley enjoys the lake, adventures, food, naps, and belly rubs.",
  "He can be grouchy at night and loves chasing squirrels, particularly his nemesis, Steve.",
  "Bongo and Oakley are best friends, playing alongside each other but not together. They are very loyal to each other."
]

[[characters]]
name = "Steve"
descriptions = [
  "Steve is a 2-year-old, squirrel.",
  "He is very energetic, loves to play, and is very friendly.",
  "Steve does not talk but he is present",
  "Steve is Oakleys nemesis and they have a love-hate relationship."
]

